services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"
      - "100.64.0.10:8443:8443"
      - "100.64.0.10:8444:8444"
      - "100.64.0.10:8445:8445"
      - "100.64.0.10:8446:8446"
      - "100.64.0.10:8447:8447"
      - "100.64.0.10:8448:8448"
      - "100.64.0.10:8449:8449"
      - "100.64.0.10:8450:8450"
      - "100.64.0.10:8451:8451"
      - "100.64.0.10:8452:8452"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data:/data
      - ./config:/config
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /opt/homelab/docs:/srv/homelab-docs:ro

    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
